# Generated by Django 2.2.5 on 2019-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_toolsUsed', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
    ]
